apiVersion: v1
kind: Service
metadata:
  labels:
    run: nginx-deploy
  name: nginx-deploy01
  namespace: default
spec:
  ports:
  - port: 8888
    protocol: TCP
    targetPort: 80
  selector:
    run: nginx-deploy01
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}

